# Generated by Django 3.1.13 on 2021-07-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20210116_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Noun'), (2, 'Verb'), (3, 'Adjective'), (4, 'Adverb'), (5, 'Phrase'), (6, 'Counter')], null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='words', to='words.Topic'),
        ),
    ]
